[package]
name = "wasrus"
version = "0.1.0"
authors = ["Kohei Yamaguchi <fix7211@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
